### ISSUE TITLE
default to import roaring?

### ISSUE THREAD

**Issue by jaffee** [pilosa/pdk#117]
Can we default usage of go-pilosa to OptImportRoaring(true)? It's definitely a significant improvement for time fields. @yuce

**Comment by yuce** [comment]
@jaffee  Sure, but I am a bit worried about making features opt-out instead of opt-in. Would it make more sense to update PDK with `OptImportRoaring(true)` instead of updating go-pilosa first ?

**Comment by jaffee** [comment]
yes, @yuce that's what I meant, sorry if I was unclear—I agree it wouldn't be wise to change go-pilosa's default behavior right now.

**Comment by yuce** [comment]
There shouldn't be any problems, but I'll check again,

**Comment by yuce** [comment]
Roaring import t is currently supported for `set`, `bool` and `time` fields. For other fields, setting `OptImportRoaring(true)` won't enable roaring. If roaring is enabled and If the index/field has `keys` enabled, translating keys for columns/rows is also enabled, which use LRU caches of batch size; so that would increase memory usage a bit.
